/**
 * Public contract barrel of the `deployments` module (WORK-023).
 *
 * This file is the ONLY supported import surface for other modules
 * and for the API layer (`IMPLEMENTATION.md` §2, `spec/contracts.md`
 * "Public module rule"). Everything else under
 * `src/modules/deployments/` is private to this module.
 *
 * WORK-023 introduces the provider-neutral deployment fabric
 * (MOD-001..004/010, ADR-0014/0015/0017):
 *
 *  - the IMMUTABLE VERSIONED `DeploymentProfile` and `DeploymentPlan`
 *    artifacts (provider-neutral modality/channel/capability/latency/
 *    resource/side-effect declarations; channel bindings name neutral
 *    adapter capability ids — vendor rails never cross);
 *  - the `Deployment` control-plane object: identity bound to
 *    application/environment/agent-version (MOD-002), pointing at ONE
 *    immutable plan version, moved between versions ONLY through
 *    guarded, journaled lifecycle operations (MOD-003: create/
 *    promote/rollback/suspend/resume/retire — idempotent,
 *    concurrency-safe, append-only evidence with actor, cause,
 *    prior/current version and execution provenance);
 *  - the modality-adapter seam (MOD-004): provider-neutral channel
 *    adapters that DESCRIBE bindings and never authorize, budget,
 *    admit or execute — duplicate authorities are unrepresentable in
 *    the port's shape;
 *  - BYOA representation (MOD-010): agent references may carry
 *    `agentKind: "byoa"` with an OPAQUE external descriptor — an
 *    external runtime is representable WITHOUT becoming a Zeck
 *    dependency.
 *
 * Deployment is Execution-ADJACENT (ADR-0014 invariant 1): nothing
 * here dispatches, executes or verifies; executions remain the runs
 * (the executions module's authority), and every deployed workload
 * ultimately executes through the existing Execution abstraction
 * under the existing policy/capability/budget/tenant/verification
 * authorities — unchanged.
 */

import type { ModuleDescriptor } from "../../shared/module";
import { createAgentInventoryAdapter } from "./adapters/agent-inventory-adapter";
import { createBudgetMediaAdmission } from "./adapters/budget-media-admission";
import { createBudgetMessagingAdmission } from "./adapters/budget-messaging-admission";
import { createBudgetRealtimeAdmission } from "./adapters/budget-realtime-admission";
import { createCapabilityMediaAdmission } from "./adapters/capability-media-admission";
import { createCapabilityMessagingAdmission } from "./adapters/capability-messaging-admission";
import { createCapabilityRealtimeAdmission } from "./adapters/capability-realtime-admission";
import { createConnectionsMediaSecretMediation } from "./adapters/connections-media-secret-mediation";
import { createConnectionsMessagingSecretMediation } from "./adapters/connections-messaging-secret-mediation";
import { createConnectionsRealtimeSecretMediation } from "./adapters/connections-realtime-secret-mediation";
import { createSqlEnvironmentResolver } from "./adapters/environment-resolver-adapter";
import { InMemoryDeploymentStore } from "./adapters/in-memory-deployment-store";
import { InMemoryMediaStore } from "./adapters/in-memory-media-store";
import { InMemoryMessagingStore } from "./adapters/in-memory-messaging-store";
import { InMemoryRealtimeStore } from "./adapters/in-memory-realtime-store";
import { createInProcessMediaRail } from "./adapters/in-process-media-rail";
import { createInProcessMessagingRail } from "./adapters/in-process-messaging-rail";
import { createInProcessRealtimeRail } from "./adapters/in-process-realtime-rail";
import { createMediaArtifactAuthorityAdapter } from "./adapters/media-artifact-authority";
import { createMediaExecutionLedgerAdapter } from "./adapters/media-execution-ledger";
import { createMediaModalityAdapter } from "./adapters/media-modality-adapter";
import { createMessagingExecutionLedgerAdapter } from "./adapters/messaging-execution-ledger";
import { createMessagingModalityAdapter } from "./adapters/messaging-modality-adapter";
import { createPlannerMessagingSubtaskRouter } from "./adapters/planner-messaging-subtask-router";
import { createPlannerSubtaskRouter } from "./adapters/planner-subtask-router";
import { createPolicyMediaAdmission } from "./adapters/policy-media-admission";
import { createPolicyMessagingAdmission } from "./adapters/policy-messaging-admission";
import { createPolicyRealtimeAdmission } from "./adapters/policy-realtime-admission";
import { createRealtimeExecutionLedgerAdapter } from "./adapters/realtime-execution-ledger";
import { createRealtimeModalityAdapter } from "./adapters/realtime-modality-adapter";
import { SqlDeploymentStore } from "./adapters/sql-deployment-store";
import { SqlMediaStore } from "./adapters/sql-media-store";
import { SqlMessagingStore } from "./adapters/sql-messaging-store";
import { SqlRealtimeStore } from "./adapters/sql-realtime-store";
import { createVerificationMediaGate } from "./adapters/verification-media-gate";
import type {
  DeploymentActor,
  DeploymentService,
  DeploymentServiceDeps,
} from "./application/deployment-service";
import { createDeploymentService } from "./application/deployment-service";
import type {
  MediaActor,
  MediaDeploymentFacts,
  MediaGenerationService,
  MediaGenerationServiceDeps,
  MediaJobCancelOutcome,
  MediaObservationApplyOutcome,
  MediaVariantOutcome,
  RetryMediaJobInput,
  SubmitMediaJobOutcome,
} from "./application/media-generation-service";
import { createMediaGenerationService } from "./application/media-generation-service";
import type {
  MessagingActor,
  MessagingConversationService,
  MessagingConversationServiceDeps,
  MessagingDeliveryApplyOutcome,
  MessagingDeploymentFacts,
  MessagingEscalationOutcome,
  MessagingIngestOutcome,
  StartMessagingConversationOutcome,
} from "./application/messaging-conversation-service";
import { createMessagingConversationService } from "./application/messaging-conversation-service";
import type {
  RealtimeActor,
  RealtimeDeploymentFacts,
  RealtimeIngestOutcome,
  RealtimeSessionService,
  RealtimeSessionServiceDeps,
  StartRealtimeSessionOutcome,
} from "./application/realtime-session-service";
import { createRealtimeSessionService } from "./application/realtime-session-service";
import type {
  CreateDeploymentInput,
  DeploymentEventKind,
  DeploymentEventRecord,
  DeploymentMutationInput,
  DeploymentStatus,
  DeploymentValidation,
  PromoteDeploymentInput,
} from "./domain/deployment";
import {
  canTransitionDeployment,
  DEPLOYMENT_EVENT_KINDS,
  DEPLOYMENT_STATUS_TRANSITIONS,
  DEPLOYMENT_STATUSES,
  deploymentCreationFingerprint,
  isDeploymentEventKind,
  isDeploymentStatus,
  isTerminalDeploymentStatus,
  validateCause,
  validateCreateDeploymentInput,
} from "./domain/deployment";
import type {
  DeriveMediaVariantInput,
  MediaArtifactRecord,
  MediaArtifactRole,
  MediaCallbackInput,
  MediaCriteriaRef,
  MediaJobRecord,
  MediaJobStatus,
  MediaObservationRecord,
  MediaObservationSource,
  MediaOperationCheckpoint,
  MediaOperationKind,
  MediaOperationRecord,
  MediaOperationStatus,
  MediaProviderObservation,
  MediaValidation,
  MediaVerificationMode,
  SubmitMediaJobInput,
} from "./domain/media";
import {
  canTransitionMediaJob,
  deterministicMediaObservationKey,
  deterministicMediaSubmissionKey,
  isCompletionObservation,
  isMediaArtifactRole,
  isMediaGenerationKind,
  isMediaJobStatus,
  isMediaObservationSource,
  isMediaOperationKind,
  isMediaOperationStatus,
  isMediaProviderObservation,
  isMediaVerificationMode,
  isTerminalMediaJobStatus,
  MEDIA_ARTIFACT_ROLES,
  MEDIA_GENERATION_KINDS,
  MEDIA_JOB_STATUSES,
  MEDIA_JOB_TRANSITIONS,
  MEDIA_OBSERVATION_SOURCES,
  MEDIA_OPERATION_KINDS,
  MEDIA_OPERATION_STATUSES,
  MEDIA_PROVIDER_OBSERVATIONS,
  MEDIA_VERIFICATION_MODES,
  mediaBudgetOperationId,
  mediaContainsRawSecretValue,
  mediaEvidenceKey,
  mediaJobCreationFingerprint,
  mediaObservationBodyDigestBase,
  mediaOperationKey,
  mediaOutputArtifactKey,
  mediaRailCancelKey,
  mediaRailDispatchKey,
  mediaVariantArtifactKey,
  mediaVerificationKey,
  postprocessMediaOutput,
  preprocessMediaJobSpec,
  validateDeriveMediaVariantInput,
  validateMediaCallbackInput,
  validateSubmitMediaJobInput,
} from "./domain/media";
import type {
  MessagingCallbackStatus,
  MessagingChannelKind,
  MessagingConversationRecord,
  MessagingConversationStatus,
  MessagingDeliveryCallbackInput,
  MessagingDeliveryRecord,
  MessagingDeliveryStatus,
  MessagingEscalationRecord,
  MessagingInboundEventInput,
  MessagingMessageDirection,
  MessagingMessageKind,
  MessagingMessageRecord,
  MessagingOperationCheckpoint,
  MessagingOperationKind,
  MessagingOperationRecord,
  MessagingOperationStatus,
  MessagingOrderingMarker,
  MessagingOrderingMode,
  MessagingRouteClass,
  MessagingValidation,
  StartMessagingConversationInput,
} from "./domain/messaging";
import {
  canTransitionMessagingConversation,
  deterministicMessagingCallbackKey,
  deterministicMessagingEventKey,
  isForwardMessagingDeliveryMove,
  isMessagingCallbackStatus,
  isMessagingChannelKind,
  isMessagingConversationStatus,
  isMessagingDeliveryStatus,
  isMessagingMessageKind,
  isMessagingOperationKind,
  isMessagingOperationStatus,
  isMessagingOrderingMarker,
  isMessagingOrderingMode,
  isMessagingRouteClass,
  isTerminalMessagingConversationStatus,
  isTerminalMessagingDeliveryStatus,
  MESSAGING_CALLBACK_STATUSES,
  MESSAGING_CHANNEL_KINDS,
  MESSAGING_CONVERSATION_STATUSES,
  MESSAGING_CONVERSATION_TRANSITIONS,
  MESSAGING_DELIVERY_STATUSES,
  MESSAGING_MESSAGE_DIRECTIONS,
  MESSAGING_MESSAGE_KINDS,
  MESSAGING_OPERATION_KINDS,
  MESSAGING_OPERATION_STATUSES,
  MESSAGING_ORDERING_MARKERS,
  MESSAGING_ORDERING_MODES,
  MESSAGING_ROUTE_CLASSES,
  messagingContainsRawSecretValue,
  messagingConversationCreationFingerprint,
  messagingMessageBodyDigestBase,
  messagingOperationKey,
  messagingRailCloseKey,
  messagingRailEscalateKey,
  messagingRailOpenKey,
  messagingRailSendKey,
  resolveMessagingOrdering,
  validateMessagingDeliveryCallback,
  validateMessagingInboundEvent,
  validateStartMessagingConversationInput,
} from "./domain/messaging";
import type {
  ChannelBinding,
  DeploymentPlan,
  DeploymentPlanInput,
  DeploymentSessionPolicy,
  PlanAgentRef,
  PlanValidation,
} from "./domain/plan";
import { canonicalPlanJson, validateDeploymentPlanInput } from "./domain/plan";
import type {
  DeploymentIoModality,
  DeploymentLatencyClass,
  DeploymentModality,
  DeploymentProfile,
  DeploymentProfileInput,
  DeploymentResourceClass,
  DeploymentSideEffectClass,
  ProfileValidation,
} from "./domain/profile";
import {
  canonicalProfileJson,
  DEPLOYMENT_CHANNEL_KINDS,
  DEPLOYMENT_IO_MODALITIES,
  DEPLOYMENT_LATENCY_CLASSES,
  DEPLOYMENT_MODALITIES,
  DEPLOYMENT_RESOURCE_CLASSES,
  DEPLOYMENT_SIDE_EFFECT_CLASSES,
  profileContainsRawSecretValue,
  validateDeploymentProfileInput,
} from "./domain/profile";
import type {
  RealtimeChannelKind,
  RealtimeEventDirection,
  RealtimeEventKind,
  RealtimeEventRecord,
  RealtimeInboundEventInput,
  RealtimeInboundKind,
  RealtimeOperationCheckpoint,
  RealtimeOperationKind,
  RealtimeOperationRecord,
  RealtimeOperationStatus,
  RealtimeRouteClass,
  RealtimeSessionRecord,
  RealtimeSessionStatus,
  RealtimeValidation,
  StartRealtimeSessionInput,
} from "./domain/realtime";
import {
  canTransitionRealtimeSession,
  deterministicRealtimeEventKey,
  isRealtimeChannelKind,
  isRealtimeEventKind,
  isRealtimeInboundKind,
  isRealtimeOperationKind,
  isRealtimeOperationStatus,
  isRealtimeRouteClass,
  isRealtimeSessionStatus,
  isTerminalRealtimeSessionStatus,
  REALTIME_CHANNEL_KINDS,
  REALTIME_EVENT_DIRECTIONS,
  REALTIME_EVENT_KINDS,
  REALTIME_INBOUND_KINDS,
  REALTIME_OPERATION_KINDS,
  REALTIME_OPERATION_STATUSES,
  REALTIME_ROUTE_CLASSES,
  REALTIME_SESSION_STATUSES,
  REALTIME_SESSION_TRANSITIONS,
  realtimeContainsRawSecretValue,
  realtimeEventBodyDigestBase,
  realtimeOperationKey,
  realtimeRailCloseKey,
  realtimeRailDeliverKey,
  realtimeRailOpenKey,
  realtimeRailTransferKey,
  realtimeSessionCreationFingerprint,
  validateRealtimeInboundEvent,
  validateStartRealtimeSessionInput,
} from "./domain/realtime";
import type { AgentVersionFact, DeploymentAgentInventory } from "./ports/agent-inventory";
import type {
  DeploymentInsertInput,
  DeploymentInsertOutcome,
  DeploymentStore,
  GuardedMutation,
  JournalAppendInput,
  PlanInsertInput,
  PlanInsertOutcome,
  ProfileInsertInput,
  ProfileInsertOutcome,
} from "./ports/deployment-store";
import type { DeploymentEnvironmentResolver, EnvironmentRef } from "./ports/environment-resolver";
import type {
  MediaAdmissionEvidence,
  MediaBudgetAdmission,
  MediaBudgetReservation,
  MediaBudgetReserveCommand,
  MediaCapabilityAdmission,
  MediaCapabilityAdmissionDecision,
  MediaCapabilityAdmissionRequest,
  MediaPolicyAction,
  MediaPolicyAdmission,
  MediaPolicyAdmissionDecision,
  MediaPolicyAdmissionRequest,
  MediaSecretMediation,
  MediaSecretMediationOutcome,
  MediaSecretMediationRequest,
} from "./ports/media-admission";
import type {
  MediaArtifactAdoptionInput,
  MediaArtifactAdoptionOutcome,
  MediaArtifactAuthority,
} from "./ports/media-artifact-authority";
import type {
  MediaEvidenceClass,
  MediaEvidenceInput,
  MediaEvidenceOutcome,
  MediaExecutionLedger,
  MediaExecutionOpenInput,
  MediaExecutionOpenOutcome,
  MediaVerificationResult,
} from "./ports/media-execution-ledger";
import type {
  MediaRail,
  MediaRailCancelOutcome,
  MediaRailCancelRequest,
  MediaRailDescriptor,
  MediaRailDispatchOutcome,
  MediaRailDispatchRequest,
  MediaRailJobCallback,
  MediaRailPollOutcome,
} from "./ports/media-rail";
import type {
  MediaArtifactInsertInput,
  MediaArtifactInsertOutcome,
  MediaJobInsertInput,
  MediaJobInsertOutcome,
  MediaJobMutation,
  MediaJobMutationOutcome,
  MediaObservationAppendInput,
  MediaObservationAppendOutcome,
  MediaOperationBeginInput,
  MediaOperationBeginOutcome,
  MediaStore,
} from "./ports/media-store";
import type {
  MediaVerificationGate,
  MediaVerificationOutcome,
  MediaVerificationRequest,
} from "./ports/media-verification";
import type {
  MessagingAdmissionEvidence,
  MessagingBudgetAdmission,
  MessagingBudgetReservation,
  MessagingBudgetReserveCommand,
  MessagingCapabilityAdmission,
  MessagingCapabilityAdmissionDecision,
  MessagingCapabilityAdmissionRequest,
  MessagingPolicyAction,
  MessagingPolicyAdmission,
  MessagingPolicyAdmissionDecision,
  MessagingPolicyAdmissionRequest,
  MessagingSecretMediation,
  MessagingSecretMediationOutcome,
  MessagingSecretMediationRequest,
} from "./ports/messaging-admission";
import type {
  MessagingEvidenceClass,
  MessagingEvidenceInput,
  MessagingEvidenceOutcome,
  MessagingExecutionLedger,
  MessagingExecutionOpenInput,
  MessagingExecutionOpenOutcome,
} from "./ports/messaging-execution-ledger";
import type {
  MessagingRail,
  MessagingRailConversation,
  MessagingRailConversationRequest,
  MessagingRailDeliveryCallback,
  MessagingRailDescriptor,
  MessagingRailEscalationRequest,
  MessagingRailMessageCallback,
  MessagingRailSendOutcome,
  MessagingRailSendRequest,
} from "./ports/messaging-rail";
import type {
  MessagingConversationInsertInput,
  MessagingConversationInsertOutcome,
  MessagingConversationMutation,
  MessagingConversationMutationOutcome,
  MessagingDeliveryAppendInput,
  MessagingDeliveryAppendOutcome,
  MessagingEscalationInsertInput,
  MessagingEscalationInsertOutcome,
  MessagingMessageAppendInput,
  MessagingMessageAppendOutcome,
  MessagingOperationBeginInput,
  MessagingOperationBeginOutcome,
  MessagingStore,
} from "./ports/messaging-store";
import type {
  MessagingSubtaskRouter,
  MessagingTurnRoute,
  MessagingTurnRouteRequest,
} from "./ports/messaging-subtask-router";
import type {
  MessagingTurnResponder,
  MessagingTurnResponderRequest,
  MessagingTurnResponse,
} from "./ports/messaging-turn-responder";
import type {
  ModalityAdapterDescriptor,
  ModalityAdapterRegistry,
  ModalityBindingCheck,
  ModalityChannelAdapter,
} from "./ports/modality-adapter";
import { createModalityAdapterRegistry } from "./ports/modality-adapter";
import type {
  RealtimeAdmissionEvidence,
  RealtimeBudgetAdmission,
  RealtimeBudgetReservation,
  RealtimeBudgetReserveCommand,
  RealtimeCapabilityAdmission,
  RealtimeCapabilityAdmissionDecision,
  RealtimeCapabilityAdmissionRequest,
  RealtimePolicyAction,
  RealtimePolicyAdmission,
  RealtimePolicyAdmissionDecision,
  RealtimePolicyAdmissionRequest,
  RealtimeSecretMediation,
  RealtimeSecretMediationOutcome,
  RealtimeSecretMediationRequest,
} from "./ports/realtime-admission";
import type {
  RealtimeEvidenceClass,
  RealtimeEvidenceInput,
  RealtimeEvidenceOutcome,
  RealtimeExecutionLedger,
  RealtimeExecutionOpenInput,
  RealtimeExecutionOpenOutcome,
} from "./ports/realtime-execution-ledger";
import type {
  RealtimeRail,
  RealtimeRailCallback,
  RealtimeRailDelivery,
  RealtimeRailDeliveryOutcome,
  RealtimeRailDescriptor,
  RealtimeRailSession,
  RealtimeRailSessionRequest,
} from "./ports/realtime-rail";
import type {
  RealtimeEventAppendInput,
  RealtimeEventAppendOutcome,
  RealtimeOperationBeginInput,
  RealtimeOperationBeginOutcome,
  RealtimeSessionInsertInput,
  RealtimeSessionInsertOutcome,
  RealtimeSessionMutation,
  RealtimeSessionMutationOutcome,
  RealtimeStore,
} from "./ports/realtime-store";
import type {
  RealtimeSubtaskRouter,
  RealtimeTurnRoute,
  RealtimeTurnRouteRequest,
} from "./ports/realtime-subtask-router";
import type {
  RealtimeTurnResponder,
  RealtimeTurnResponderRequest,
  RealtimeTurnResponse,
} from "./ports/realtime-turn-responder";

export const moduleDescriptor: ModuleDescriptor = { id: "deployments" };

export type {
  AgentVersionFact,
  ChannelBinding,
  CreateDeploymentInput,
  DeploymentActor,
  DeploymentAgentInventory,
  DeploymentEnvironmentResolver,
  DeploymentEventKind,
  DeploymentEventRecord,
  DeploymentInsertInput,
  DeploymentInsertOutcome,
  DeploymentIoModality,
  DeploymentLatencyClass,
  DeploymentModality,
  DeploymentMutationInput,
  DeploymentPlan,
  DeploymentPlanInput,
  DeploymentProfile,
  DeploymentProfileInput,
  DeploymentResourceClass,
  DeploymentService,
  DeploymentServiceDeps,
  DeploymentSessionPolicy,
  DeploymentSideEffectClass,
  DeploymentStatus,
  DeploymentStore,
  DeploymentValidation,
  // ---- WORK-026: provider-neutral media generation (MOD-011/012/013) ----
  DeriveMediaVariantInput,
  EnvironmentRef,
  GuardedMutation,
  JournalAppendInput,
  MediaActor,
  MediaAdmissionEvidence,
  MediaArtifactAdoptionInput,
  MediaArtifactAdoptionOutcome,
  MediaArtifactAuthority,
  MediaArtifactInsertInput,
  MediaArtifactInsertOutcome,
  MediaArtifactRecord,
  MediaArtifactRole,
  MediaBudgetAdmission,
  MediaBudgetReservation,
  MediaBudgetReserveCommand,
  MediaCallbackInput,
  MediaCapabilityAdmission,
  MediaCapabilityAdmissionDecision,
  MediaCapabilityAdmissionRequest,
  MediaCriteriaRef,
  MediaDeploymentFacts,
  MediaEvidenceClass,
  MediaEvidenceInput,
  MediaEvidenceOutcome,
  MediaExecutionLedger,
  MediaExecutionOpenInput,
  MediaExecutionOpenOutcome,
  MediaGenerationService,
  MediaGenerationServiceDeps,
  MediaJobCancelOutcome,
  MediaJobInsertInput,
  MediaJobInsertOutcome,
  MediaJobMutation,
  MediaJobMutationOutcome,
  MediaJobRecord,
  MediaJobStatus,
  MediaObservationAppendInput,
  MediaObservationAppendOutcome,
  MediaObservationApplyOutcome,
  MediaObservationRecord,
  MediaObservationSource,
  MediaOperationBeginInput,
  MediaOperationBeginOutcome,
  MediaOperationCheckpoint,
  MediaOperationKind,
  MediaOperationRecord,
  MediaOperationStatus,
  MediaPolicyAction,
  MediaPolicyAdmission,
  MediaPolicyAdmissionDecision,
  MediaPolicyAdmissionRequest,
  MediaProviderObservation,
  MediaRail,
  MediaRailCancelOutcome,
  MediaRailCancelRequest,
  MediaRailDescriptor,
  MediaRailDispatchOutcome,
  MediaRailDispatchRequest,
  MediaRailJobCallback,
  MediaRailPollOutcome,
  MediaSecretMediation,
  MediaSecretMediationOutcome,
  MediaSecretMediationRequest,
  MediaStore,
  MediaValidation,
  MediaVariantOutcome,
  MediaVerificationGate,
  MediaVerificationMode,
  MediaVerificationOutcome,
  MediaVerificationRequest,
  MediaVerificationResult,
  // ---- WORK-025: provider-neutral conversational messaging (MOD-008/009) ----
  MessagingActor,
  MessagingAdmissionEvidence,
  MessagingBudgetAdmission,
  MessagingBudgetReservation,
  MessagingBudgetReserveCommand,
  MessagingCallbackStatus,
  MessagingCapabilityAdmission,
  MessagingCapabilityAdmissionDecision,
  MessagingCapabilityAdmissionRequest,
  MessagingChannelKind,
  MessagingConversationInsertInput,
  MessagingConversationInsertOutcome,
  MessagingConversationMutation,
  MessagingConversationMutationOutcome,
  MessagingConversationRecord,
  MessagingConversationService,
  MessagingConversationServiceDeps,
  MessagingConversationStatus,
  MessagingDeliveryAppendInput,
  MessagingDeliveryAppendOutcome,
  MessagingDeliveryApplyOutcome,
  MessagingDeliveryCallbackInput,
  MessagingDeliveryRecord,
  MessagingDeliveryStatus,
  MessagingDeploymentFacts,
  MessagingEscalationInsertInput,
  MessagingEscalationInsertOutcome,
  MessagingEscalationOutcome,
  MessagingEscalationRecord,
  MessagingEvidenceClass,
  MessagingEvidenceInput,
  MessagingEvidenceOutcome,
  MessagingExecutionLedger,
  MessagingExecutionOpenInput,
  MessagingExecutionOpenOutcome,
  MessagingInboundEventInput,
  MessagingIngestOutcome,
  MessagingMessageAppendInput,
  MessagingMessageAppendOutcome,
  MessagingMessageDirection,
  MessagingMessageKind,
  MessagingMessageRecord,
  MessagingOperationBeginInput,
  MessagingOperationBeginOutcome,
  MessagingOperationCheckpoint,
  MessagingOperationKind,
  MessagingOperationRecord,
  MessagingOperationStatus,
  MessagingOrderingMarker,
  MessagingOrderingMode,
  MessagingPolicyAction,
  MessagingPolicyAdmission,
  MessagingPolicyAdmissionDecision,
  MessagingPolicyAdmissionRequest,
  MessagingRail,
  MessagingRailConversation,
  MessagingRailConversationRequest,
  MessagingRailDeliveryCallback,
  MessagingRailDescriptor,
  MessagingRailEscalationRequest,
  MessagingRailMessageCallback,
  MessagingRailSendOutcome,
  MessagingRailSendRequest,
  MessagingRouteClass,
  MessagingSecretMediation,
  MessagingSecretMediationOutcome,
  MessagingSecretMediationRequest,
  MessagingStore,
  MessagingSubtaskRouter,
  MessagingTurnResponder,
  MessagingTurnResponderRequest,
  MessagingTurnResponse,
  MessagingTurnRoute,
  MessagingTurnRouteRequest,
  MessagingValidation,
  ModalityAdapterDescriptor,
  ModalityAdapterRegistry,
  ModalityBindingCheck,
  ModalityChannelAdapter,
  PlanAgentRef,
  PlanInsertInput,
  PlanInsertOutcome,
  PlanValidation,
  ProfileInsertInput,
  ProfileInsertOutcome,
  ProfileValidation,
  PromoteDeploymentInput,
  // ---- WORK-024: realtime voice sessions (MOD-005/006/007) ----
  RealtimeActor,
  RealtimeAdmissionEvidence,
  RealtimeBudgetAdmission,
  RealtimeBudgetReservation,
  RealtimeBudgetReserveCommand,
  RealtimeCapabilityAdmission,
  RealtimeCapabilityAdmissionDecision,
  RealtimeCapabilityAdmissionRequest,
  RealtimeChannelKind,
  RealtimeDeploymentFacts,
  RealtimeEventAppendInput,
  RealtimeEventAppendOutcome,
  RealtimeEventDirection,
  RealtimeEventKind,
  RealtimeEventRecord,
  RealtimeEvidenceClass,
  RealtimeEvidenceInput,
  RealtimeEvidenceOutcome,
  RealtimeExecutionLedger,
  RealtimeExecutionOpenInput,
  RealtimeExecutionOpenOutcome,
  RealtimeInboundEventInput,
  RealtimeInboundKind,
  RealtimeIngestOutcome,
  RealtimeOperationBeginInput,
  RealtimeOperationBeginOutcome,
  RealtimeOperationCheckpoint,
  RealtimeOperationKind,
  RealtimeOperationRecord,
  RealtimeOperationStatus,
  RealtimePolicyAction,
  RealtimePolicyAdmission,
  RealtimePolicyAdmissionDecision,
  RealtimePolicyAdmissionRequest,
  RealtimeRail,
  RealtimeRailCallback,
  RealtimeRailDelivery,
  RealtimeRailDeliveryOutcome,
  RealtimeRailDescriptor,
  RealtimeRailSession,
  RealtimeRailSessionRequest,
  RealtimeRouteClass,
  RealtimeSecretMediation,
  RealtimeSecretMediationOutcome,
  RealtimeSecretMediationRequest,
  RealtimeSessionInsertInput,
  RealtimeSessionInsertOutcome,
  RealtimeSessionMutation,
  RealtimeSessionMutationOutcome,
  RealtimeSessionRecord,
  RealtimeSessionService,
  RealtimeSessionServiceDeps,
  RealtimeSessionStatus,
  RealtimeStore,
  RealtimeSubtaskRouter,
  RealtimeTurnResponder,
  RealtimeTurnResponderRequest,
  RealtimeTurnResponse,
  RealtimeTurnRoute,
  RealtimeTurnRouteRequest,
  RealtimeValidation,
  RetryMediaJobInput,
  StartMessagingConversationInput,
  StartMessagingConversationOutcome,
  StartRealtimeSessionInput,
  StartRealtimeSessionOutcome,
  SubmitMediaJobInput,
  SubmitMediaJobOutcome,
};
// Adapters are re-exported for composition roots (the WORK-003/005/007
// precedent: factories and provider-neutral adapters cross the barrel;
// provider SDK types never do).
export {
  canonicalPlanJson,
  canonicalProfileJson,
  canTransitionDeployment,
  canTransitionMediaJob,
  canTransitionMessagingConversation,
  canTransitionRealtimeSession,
  createAgentInventoryAdapter,
  createBudgetMediaAdmission,
  createBudgetMessagingAdmission,
  createBudgetRealtimeAdmission,
  createCapabilityMediaAdmission,
  createCapabilityMessagingAdmission,
  createCapabilityRealtimeAdmission,
  createConnectionsMediaSecretMediation,
  createConnectionsMessagingSecretMediation,
  createConnectionsRealtimeSecretMediation,
  createDeploymentService,
  createInProcessMediaRail,
  createInProcessMessagingRail,
  createInProcessRealtimeRail,
  createMediaArtifactAuthorityAdapter,
  createMediaExecutionLedgerAdapter,
  createMediaGenerationService,
  createMediaModalityAdapter,
  createMessagingConversationService,
  createMessagingExecutionLedgerAdapter,
  createMessagingModalityAdapter,
  createModalityAdapterRegistry,
  createPlannerMessagingSubtaskRouter,
  createPlannerSubtaskRouter,
  createPolicyMediaAdmission,
  createPolicyMessagingAdmission,
  createPolicyRealtimeAdmission,
  createRealtimeExecutionLedgerAdapter,
  createRealtimeModalityAdapter,
  createRealtimeSessionService,
  createSqlEnvironmentResolver,
  createVerificationMediaGate,
  DEPLOYMENT_CHANNEL_KINDS,
  DEPLOYMENT_EVENT_KINDS,
  DEPLOYMENT_IO_MODALITIES,
  DEPLOYMENT_LATENCY_CLASSES,
  DEPLOYMENT_MODALITIES,
  DEPLOYMENT_RESOURCE_CLASSES,
  DEPLOYMENT_SIDE_EFFECT_CLASSES,
  DEPLOYMENT_STATUS_TRANSITIONS,
  DEPLOYMENT_STATUSES,
  deploymentCreationFingerprint,
  deterministicMediaObservationKey,
  deterministicMediaSubmissionKey,
  deterministicMessagingCallbackKey,
  deterministicMessagingEventKey,
  deterministicRealtimeEventKey,
  InMemoryDeploymentStore,
  InMemoryMediaStore,
  InMemoryMessagingStore,
  InMemoryRealtimeStore,
  isCompletionObservation,
  isDeploymentEventKind,
  isDeploymentStatus,
  isForwardMessagingDeliveryMove,
  isMediaArtifactRole,
  isMediaGenerationKind,
  isMediaJobStatus,
  isMediaObservationSource,
  isMediaOperationKind,
  isMediaOperationStatus,
  isMediaProviderObservation,
  isMediaVerificationMode,
  isMessagingCallbackStatus,
  isMessagingChannelKind,
  isMessagingConversationStatus,
  isMessagingDeliveryStatus,
  isMessagingMessageKind,
  isMessagingOperationKind,
  isMessagingOperationStatus,
  isMessagingOrderingMarker,
  isMessagingOrderingMode,
  isMessagingRouteClass,
  isRealtimeChannelKind,
  isRealtimeEventKind,
  isRealtimeInboundKind,
  isRealtimeOperationKind,
  isRealtimeOperationStatus,
  isRealtimeRouteClass,
  isRealtimeSessionStatus,
  isTerminalDeploymentStatus,
  isTerminalMediaJobStatus,
  isTerminalMessagingConversationStatus,
  isTerminalMessagingDeliveryStatus,
  isTerminalRealtimeSessionStatus,
  MEDIA_ARTIFACT_ROLES,
  MEDIA_GENERATION_KINDS,
  MEDIA_JOB_STATUSES,
  MEDIA_JOB_TRANSITIONS,
  MEDIA_OBSERVATION_SOURCES,
  MEDIA_OPERATION_KINDS,
  MEDIA_OPERATION_STATUSES,
  MEDIA_PROVIDER_OBSERVATIONS,
  MEDIA_VERIFICATION_MODES,
  MESSAGING_CALLBACK_STATUSES,
  MESSAGING_CHANNEL_KINDS,
  MESSAGING_CONVERSATION_STATUSES,
  MESSAGING_CONVERSATION_TRANSITIONS,
  MESSAGING_DELIVERY_STATUSES,
  MESSAGING_MESSAGE_DIRECTIONS,
  MESSAGING_MESSAGE_KINDS,
  MESSAGING_OPERATION_KINDS,
  MESSAGING_OPERATION_STATUSES,
  MESSAGING_ORDERING_MARKERS,
  MESSAGING_ORDERING_MODES,
  MESSAGING_ROUTE_CLASSES,
  mediaBudgetOperationId,
  mediaContainsRawSecretValue,
  mediaEvidenceKey,
  mediaJobCreationFingerprint,
  mediaObservationBodyDigestBase,
  mediaOperationKey,
  mediaOutputArtifactKey,
  mediaRailCancelKey,
  mediaRailDispatchKey,
  mediaVariantArtifactKey,
  mediaVerificationKey,
  messagingContainsRawSecretValue,
  messagingConversationCreationFingerprint,
  messagingMessageBodyDigestBase,
  messagingOperationKey,
  messagingRailCloseKey,
  messagingRailEscalateKey,
  messagingRailOpenKey,
  messagingRailSendKey,
  postprocessMediaOutput,
  preprocessMediaJobSpec,
  profileContainsRawSecretValue,
  REALTIME_CHANNEL_KINDS,
  REALTIME_EVENT_DIRECTIONS,
  REALTIME_EVENT_KINDS,
  REALTIME_INBOUND_KINDS,
  REALTIME_OPERATION_KINDS,
  REALTIME_OPERATION_STATUSES,
  REALTIME_ROUTE_CLASSES,
  REALTIME_SESSION_STATUSES,
  REALTIME_SESSION_TRANSITIONS,
  realtimeContainsRawSecretValue,
  realtimeEventBodyDigestBase,
  realtimeOperationKey,
  realtimeRailCloseKey,
  realtimeRailDeliverKey,
  realtimeRailOpenKey,
  realtimeRailTransferKey,
  realtimeSessionCreationFingerprint,
  resolveMessagingOrdering,
  SqlDeploymentStore,
  SqlMediaStore,
  SqlMessagingStore,
  SqlRealtimeStore,
  validateCause,
  validateCreateDeploymentInput,
  validateDeploymentPlanInput,
  validateDeploymentProfileInput,
  validateDeriveMediaVariantInput,
  validateMediaCallbackInput,
  validateMessagingDeliveryCallback,
  validateMessagingInboundEvent,
  validateRealtimeInboundEvent,
  validateStartMessagingConversationInput,
  validateStartRealtimeSessionInput,
  validateSubmitMediaJobInput,
};
