/**
 * The PPR-022 representative general-agent corpus — small, real,
 * mechanically verifiable tasks of the kind Hermes-Agent exists for, each
 * designed to exercise one declared execution-graph edge through the
 * REAL pinned Hermes runtime (one-shot `hermes -z` runs — the app's own
 * headless user surface — plus the pinned transcription surface driven
 * through its own module entry):
 *
 *  1. implement-edit      (hermes.agent-loop.main +
 *     hermes.auxiliary.title-generation) — a real code edit through the
 *     agent's write_file/terminal tools + a verification command the
 *     agent runs itself; every fresh session also fires the automatic
 *     title-generation aux call;
 *  2. vision-qa           (hermes.auxiliary.vision-analyze) — the agent
 *     must load a local image with the vision_analyze tool and answer a
 *     question about it (the aux vision path — the custom provider
 *     profile declares no native vision);
 *  3. context-compaction  (hermes.auxiliary.compression +
 *     hermes.agent-loop.main) — a multi-file read+append task run with a
 *     small context_length + compression threshold so the compressor's
 *     own summarization call fires mid-task;
 *  4. speak-text          (hermes.tool.tts-openai) — the agent must
 *     synthesize speech through the text_to_speech tool into an output
 *     path; verification reads the audio artifact (RIFF/WAV header +
 *     duration sanity);
 *  5. transcribe-memo     (hermes.tool.stt-openai) — a voice memo
 *     (the corpus's known-phrase fixture, generated by the same supply's
 *     TTS surface at corpus-build time) transcribed through the pinned
 *     runtime's own transcribe_audio surface;
 *  6. generate-image      (hermes.tool.image-generate-openai) — the
 *     agent must generate an image through the image_generate tool;
 *     verification reads the cached image artifact (PNG/JPEG magic +
 *     plausible dimensions).
 *
 * Every task carries: the fresh-workspace fixture builder (pure
 * filesystem writes), the driver task-spec fragment (instruction,
 * toolsets, runtime config axes), and a MECHANICAL verifier
 * (deterministic checks over the workspace + run result — never an LLM
 * judging an LLM).
 */

import { execSync } from "node:child_process";
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/** The corpus root (this file's directory). */
const CORPUS_ROOT = dirname(fileURLToPath(import.meta.url));

/** The vision fixture (a deterministic 64×64 solid-orange PNG). */
export const VISION_SWATCH_PATH = join(CORPUS_ROOT, "assets", "orange-swatch.png");

/** The voice-memo fixture (the supply TTS surface's own rendering of a known phrase). */
export const KNOWN_PHRASE_WAV_PATH = join(CORPUS_ROOT, "assets", "known-phrase.wav");

/** The known transcript the STT verifier expects (recorded at fixture build time). */
export const KNOWN_PHRASE_TEXT = "Proof of life, Hermes test one.";

/**
 * The model id the corpus's configuration carries (an opaque neutral
 * string to Hermes; the rail owns the actual supply model).
 */
export const CORPUS_MODEL_ID = "glm-4-plus";

/** The placeholder the openai SDK's shape check requires (never a credential). */
export const CORPUS_API_KEY_PLACEHOLDER = "zeck-local-adapter";

/** The env-var NAME the image-gen openai plugin's key_env axis points at (a placeholder value). */
export const CORPUS_IMAGE_KEY_ENV = "HERMES_IMAGE_KEY";

export interface CorpusTask {
  readonly taskId: string;
  readonly title: string;
  /** The driver task-spec fragment (instruction, toolsets, runtime axes). */
  readonly spec: {
    readonly instruction: string;
    /** The `-t/--toolsets` value for the one-shot run. */
    readonly toolsets: string;
    /** Extra model/runtime config axes for this task's HERMES_HOME config.yaml. */
    readonly contextLength?: number;
    readonly compressionThreshold?: number;
    /** The compression.threshold_tokens absolute cap (fires at the LOWER of ratio vs cap). */
    readonly compressionTokenCap?: number;
    readonly maxTurns?: number;
  };
  /** Build the fresh workspace fixture. */
  readonly fixture: (workdir: string) => void;
  /** Mechanically verify the outcome (workspace + run result). */
  readonly verify: (input: {
    readonly workdir: string;
    readonly home: string;
    readonly stdout: string;
    readonly stderr: string;
    readonly exitCode: number;
  }) => { readonly resolved: boolean; readonly checkOutput: string };
}

// ---------------------------------------------------------------------------
// Task 1 — implement + verify edit (hermes.agent-loop.main + title aux)
// ---------------------------------------------------------------------------

const IMPLEMENT_EDIT: CorpusTask = {
  taskId: "implement-edit",
  title: "Agent loop: implement a scoring function and verify it",
  spec: {
    instruction:
      "Implement the function wordScore(word) in game.js exactly as documented in its docstring, " +
      "then run the command `node verify.js` with the terminal tool and confirm it prints GAME-OK.",
    toolsets: "file,terminal",
    maxTurns: 40,
  },
  fixture(workdir) {
    writeFileSync(
      join(workdir, "game.js"),
      [
        "/**",
        " * Score a word for a word game.",
        " *",
        " * The score is the sum of letter values: vowels (a, e, i, o, u) are worth",
        " * 1 point each; every other lowercase letter is worth 3 points. Characters",
        " * that are not lowercase letters (uppercase, digits, punctuation, spaces)",
        " * are worth 0 points.",
        " */",
        "function wordScore(word) {",
        "  // TODO: implement per the docstring above",
        "}",
        "",
        "module.exports = { wordScore };",
        "",
      ].join("\n"),
    );
    writeFileSync(
      join(workdir, "verify.js"),
      [
        "const { wordScore } = require('./game.js');",
        "// abc: a=1 b=3 c=3 = 7; aeiou = 5; Zz! = 3 (Z=0 z=3 != 0); '' = 0;",
        "// hello world: h=3 e=1 l=3 l=3 o=1 (space=0) w=3 o=1 r=3 l=3 d=3 = 24",
        "const fixed = [",
        "  ['abc', 7], ['aeiou', 5], ['Zz!', 3], ['', 0], ['hello world', 24],",
        "];",
        "let ok = true;",
        "for (const [word, expected] of fixed) {",
        "  const got = wordScore(word);",
        "  if (got !== expected) { ok = false; console.error(`FAIL ${JSON.stringify(word)}: expected ${expected}, got ${got}`); }",
        "}",
        "console.log(ok ? 'GAME-OK' : 'GAME-FAIL');",
        "process.exit(ok ? 0 : 1);",
        "",
      ].join("\n"),
    );
  },
  verify({ workdir }) {
    const gamePath = join(workdir, "game.js");
    if (!existsSync(gamePath)) {
      return { resolved: false, checkOutput: "game.js missing" };
    }
    const source = readFileSync(gamePath, "utf8");
    if (/TODO: implement/.test(source)) {
      return { resolved: false, checkOutput: "game.js still contains the TODO stub" };
    }
    try {
      const out = execSync("node verify.js", { cwd: workdir, timeout: 30_000 }).toString();
      const ok = out.includes("GAME-OK");
      return {
        resolved: ok,
        checkOutput: ok ? "T1 ok (verify.js → GAME-OK)" : `verify.js output: ${out.trim()}`,
      };
    } catch (error) {
      return {
        resolved: false,
        checkOutput: `verify.js failed: ${error instanceof Error ? error.message : String(error)}`,
      };
    }
  },
};

// ---------------------------------------------------------------------------
// Task 2 — vision QA (hermes.auxiliary.vision-analyze)
// ---------------------------------------------------------------------------

const VISION_QA: CorpusTask = {
  taskId: "vision-qa",
  title: "Auxiliary vision: identify the dominant color of a local image",
  spec: {
    instruction:
      "Use the vision_analyze tool on the local file orange-swatch.png in the current " +
      "directory and answer the question: 'What is the dominant color of this image?' " +
      "Your final message must contain just the color name.",
    toolsets: "vision",
    maxTurns: 15,
  },
  fixture(workdir) {
    copyFileSync(VISION_SWATCH_PATH, join(workdir, "orange-swatch.png"));
  },
  verify({ workdir, stdout, exitCode }) {
    if (!existsSync(join(workdir, "orange-swatch.png"))) {
      return { resolved: false, checkOutput: "fixture image missing" };
    }
    if (exitCode !== 0) {
      return { resolved: false, checkOutput: `exit code ${exitCode}` };
    }
    const saidOrange = /orange/i.test(stdout);
    return {
      resolved: saidOrange,
      checkOutput: saidOrange
        ? "T2 ok (final answer names the color)"
        : `answer did not name the color (stdout tail: ${stdout.slice(-160).replace(/\s+/g, " ")})`,
    };
  },
};

// ---------------------------------------------------------------------------
// Task 3 — context compaction (hermes.auxiliary.compression)
// ---------------------------------------------------------------------------

const COMPACTION_FILES = [
  {
    name: "a.txt",
    firstWord: "alpha",
    body: "alpha report: the northern sensor array recorded 12 stable readings during the observation window, with no anomalies worth escalation in this cycle of monitoring work.\n".repeat(100),
  },
  {
    name: "b.txt",
    firstWord: "bravo",
    body: "bravo report: the southern depot confirmed inventory of 48 crates, all labeled and stacked according to the revised floor plan that was published last month for the crew.\n".repeat(100),
  },
  {
    name: "c.txt",
    firstWord: "charlie",
    body: "charlie report: the eastern route inspection found the bridge clearance unchanged at 4.2 meters, matching the registry entry that the survey team filed earlier this year.\n".repeat(100),
  },
  {
    name: "d.txt",
    firstWord: "delta",
    body: "delta report: the western gate log shows 9 deliveries accepted and 2 turned away for missing paperwork, consistent with the quarterly trend the office tracks.\n".repeat(100),
  },
];

const CONTEXT_COMPACTION: CorpusTask = {
  taskId: "context-compaction",
  title: "Compression: multi-file read+append under a small context window",
  spec: {
    instruction:
      "Process the four report files a.txt, b.txt, c.txt and d.txt STRICTLY one at a time, " +
      "in this exact order: (1) read a.txt, then append its FIRST word as a new line to " +
      "notes/words.txt; (2) read b.txt, append its first word; (3) read c.txt, append " +
      "its first word; (4) read d.txt, append its first word — one read and one append per " +
      "file, never batched. After all four are processed, RE-READ notes/words.txt from disk " +
      "and create summary.txt containing exactly the lines you see there, in order (do not " +
      "rely on your memory of earlier turns — the durable file is the source of truth).",
    toolsets: "file",
    // A small-but-legal context window + threshold fires the compressor's
    // own summarization call mid-task (the app's own configuration axes).
    // The pinned runtime ENFORCES a minimum 64,000-token window (live-
    // verified: 16,384 is refused at startup) and its ratio math floors
    // every trigger at ~85% of the effective budget — so the documented
    // compression.threshold_tokens cap pins the trigger low enough that
    // the growing session crosses it mid-task. CAP SIZING (live-measured
    // boundary, instrumented diagnostic + battery runs 2026-09-30): the
    // runtime's rough chars/4 estimate OVERSTATES the real prompt by
    // ~2.5k tokens, and the preflight deferral architecture fires
    // compression only once the provider's REAL usage crosses the cap
    // with a successor call — at cap 15,000 the leanest observed model
    // path kept real usage under the cap until the final call (no
    // successor → the edge never fired, battery run 3); at cap 10,000
    // every re-crossing re-fires the compressor and the live divergence
    // tail drained a whole 30-request supply window into 15s cooldown
    // crawls (task wall-clock timeout, battery run 4). At cap 12,000 the
    // SECOND full fixture read lands real usage at ~15k — over the cap
    // with the read/append/re-read tail still ahead — so the compressor
    // fires 2–3 passes deterministically regardless of read strategy,
    // while staying above the ~7k incompressible system+tools floor (no
    // anti-thrash trip) and inside one supply window (no crawl).
    contextLength: 65_536,
    compressionThreshold: 0.3,
    compressionTokenCap: 12_000,
    maxTurns: 60,
  },
  fixture(workdir) {
    mkdirSync(join(workdir, "notes"), { recursive: true });
    writeFileSync(join(workdir, "notes", "words.txt"), "");
    for (const file of COMPACTION_FILES) {
      writeFileSync(join(workdir, file.name), file.body);
    }
  },
  verify({ workdir }) {
    const summaryPath = join(workdir, "summary.txt");
    if (!existsSync(summaryPath)) {
      return { resolved: false, checkOutput: "summary.txt missing" };
    }
    const content = readFileSync(summaryPath, "utf8");
    const words = content
      .split(/\r?\n/)
      .map((line) => line.trim().toLowerCase())
      .filter((line) => line.length > 0);
    const expected = COMPACTION_FILES.map((file) => file.firstWord);
    const ok = words.length === 4 && expected.every((word, index) => words[index] === word);
    return {
      resolved: ok,
      checkOutput: ok
        ? "T3 ok (summary.txt = alpha/bravo/charlie/delta)"
        : `summary.txt lines: ${JSON.stringify(words)}`,
    };
  },
};

// ---------------------------------------------------------------------------
// Task 4 — speech synthesis (hermes.tool.tts-openai)
// ---------------------------------------------------------------------------

const SPEAK_TEXT: CorpusTask = {
  taskId: "speak-text",
  title: "TTS: synthesize a spoken confirmation through the text_to_speech tool",
  spec: {
    instruction:
      "Use the text_to_speech tool to synthesize exactly this text: 'The Hermes proof is " +
      "complete and every surface is delegated.' Save the audio with output_path set to " +
      "'spoken.wav' (a relative path — it lands in the current directory). Your final " +
      "message must confirm the audio file was created.",
    toolsets: "tts",
    maxTurns: 15,
  },
  fixture(workdir) {
    writeFileSync(join(workdir, "task.txt"), "synthesize: The Hermes proof is complete.\n");
  },
  verify({ workdir, home, stdout }) {
    const candidates = [join(workdir, "spoken.wav"), join(home, "voice-memos", "spoken.wav")];
    const path = candidates.find((candidate) => existsSync(candidate));
    if (path === undefined) {
      return {
        resolved: false,
        checkOutput: `no spoken.wav artifact (workspace ${join(workdir, "spoken.wav")} nor ${join(home, "voice-memos", "spoken.wav")}; stdout tail: ${stdout.slice(-160).replace(/\s+/g, " ")})`,
      };
    }
    const data = readFileSync(path);
    if (data.length < 2000) {
      return { resolved: false, checkOutput: `audio artifact too small (${data.length} bytes)` };
    }
    // A RIFF/WAV header check (the supply's default format is wav).
    const isRiff =
      data.length > 44 &&
      data[0] === 0x52 &&
      data[1] === 0x49 &&
      data[2] === 0x46 &&
      data[3] === 0x46;
    if (!isRiff) {
      return {
        resolved: false,
        checkOutput: `audio artifact is not RIFF/WAV (first bytes: ${data.subarray(0, 4).toString("hex")})`,
      };
    }
    return {
      resolved: true,
      checkOutput: `T4 ok (${path.slice(workdir.length > 0 && path.startsWith(workdir) ? workdir.length : 0)} — ${data.length} bytes, RIFF/WAV)`,
    };
  },
};

// ---------------------------------------------------------------------------
// Task 5 — voice-memo transcription (hermes.tool.stt-openai)
// ---------------------------------------------------------------------------

const TRANSCRIBE_MEMO: CorpusTask = {
  taskId: "transcribe-memo",
  title: "STT: transcribe a voice memo through the pinned runtime's transcription surface",
  spec: {
    instruction: "",
    toolsets: "",
    maxTurns: 1,
  },
  fixture(workdir) {
    copyFileSync(KNOWN_PHRASE_WAV_PATH, join(workdir, "voice-memo.wav"));
  },
  verify({ workdir, stdout }) {
    const line = stdout
      .split("\n")
      .reverse()
      .find((l) => l.startsWith("HERMES_MEDIA:"));
    if (line === undefined) {
      return { resolved: false, checkOutput: "no HERMES_MEDIA result line on stdout" };
    }
    let parsed: { ok?: unknown; transcript?: unknown; provider?: unknown; error?: unknown };
    try {
      parsed = JSON.parse(line.slice("HERMES_MEDIA:".length)) as typeof parsed;
    } catch {
      return { resolved: false, checkOutput: "unparseable HERMES_MEDIA result line" };
    }
    if (parsed.ok !== true) {
      return {
        resolved: false,
        checkOutput: `transcription failed: ${String(parsed.error ?? "unknown").slice(0, 200)}`,
      };
    }
    const transcript = String(parsed.transcript ?? "");
    const lower = transcript.toLowerCase();
    const expected = KNOWN_PHRASE_TEXT.toLowerCase();
    const words = expected.split(/\s+/).filter((word) => /[a-z]/.test(word));
    const hits = words.filter((word) => lower.includes(word)).length;
    const ok = hits >= Math.ceil(words.length * 0.7);
    return {
      resolved: ok,
      checkOutput: ok
        ? `T5 ok (provider=${String(parsed.provider)}: "${transcript.slice(0, 80)}")`
        : `transcript did not match the known phrase (got "${transcript.slice(0, 120)}")`,
    };
  },
};

// ---------------------------------------------------------------------------
// Task 6 — image generation (hermes.tool.image-generate-openai)
// ---------------------------------------------------------------------------

const GENERATE_IMAGE: CorpusTask = {
  taskId: "generate-image",
  title: "Image generation: draw a simple icon through the image_generate tool",
  spec: {
    instruction:
      "Use the image_generate tool to create an image with this prompt: 'a flat minimal " +
      "vector icon of a single teal circle centered on a white background'. Use the square " +
      "aspect ratio. Your final message must confirm the image was generated and report " +
      "the path where it was saved.",
    toolsets: "image_gen",
    maxTurns: 15,
  },
  fixture(workdir) {
    writeFileSync(join(workdir, "task.txt"), "draw: teal circle icon\n");
  },
  verify({ home, stdout }) {
    const imagesDir = join(home, "cache", "images");
    if (!existsSync(imagesDir)) {
      return {
        resolved: false,
        checkOutput: `no image cache directory at ${imagesDir} (stdout tail: ${stdout.slice(-160).replace(/\s+/g, " ")})`,
      };
    }
    const { readdirSync, statSync } = require("node:fs") as typeof import("node:fs");
    const entries = readdirSync(imagesDir)
      .map((name) => join(imagesDir, name))
      .filter((path) => statSync(path).isFile())
      .sort((a, b) => statSync(b).mtimeMs - statSync(a).mtimeMs);
    const newest = entries[0];
    if (newest === undefined) {
      return { resolved: false, checkOutput: "image cache directory is empty" };
    }
    const data = readFileSync(newest);
    if (data.length < 5000) {
      return { resolved: false, checkOutput: `image artifact too small (${data.length} bytes)` };
    }
    // PNG or JPEG magic (the supply serves JPEG bytes under a .png name —
    // disclosed; the verifier accepts both magics).
    const isPng = data[0] === 0x89 && data[1] === 0x50 && data[2] === 0x4e && data[3] === 0x47;
    const isJpeg = data[0] === 0xff && data[1] === 0xd8 && data[2] === 0xff;
    if (!isPng && !isJpeg) {
      return {
        resolved: false,
        checkOutput: `artifact is neither PNG nor JPEG (first bytes: ${data.subarray(0, 4).toString("hex")})`,
      };
    }
    return {
      resolved: true,
      checkOutput: `T6 ok (${newest} — ${data.length} bytes, ${isPng ? "PNG" : "JPEG"})`,
    };
  },
};

/** The full declared corpus (order = run order). */
export const CORPUS_TASKS: readonly CorpusTask[] = [
  IMPLEMENT_EDIT,
  VISION_QA,
  CONTEXT_COMPACTION,
  SPEAK_TEXT,
  TRANSCRIBE_MEMO,
  GENERATE_IMAGE,
];

/** A tiny probe task for the duplicate/reuse and failure batteries. */
export const DUPLICATE_PROBE_TASK: CorpusTask = {
  taskId: "duplicate-probe",
  title: "Duplicate/reuse probe: a one-turn deterministic question",
  spec: {
    instruction: "What is 2+2? Answer with just the number in your final message.",
    toolsets: "todo",
    maxTurns: 10,
  },
  fixture(workdir) {
    writeFileSync(join(workdir, "probe.txt"), "2+2\n");
  },
  verify({ stdout, exitCode }) {
    const ok = exitCode === 0 && /4/.test(stdout);
    return { resolved: ok, checkOutput: ok ? "probe ok" : "probe failed" };
  },
};
