/**
 * SQL adapter for the models dispatch journal (WORK-003, CON-005).
 *
 * Durable evidence of dispatch attempts over the provider-neutral platform
 * `DatabasePort`: intent rows commit BEFORE the adapter call; outcomes
 * commit after observation; denial rows record admission rejections. The
 * `outcome_class` CHECK (migration 0002) makes the provider axis physical —
 * quality/verification classes are unrepresentable here, which is the
 * durable half of the CON-005 proof.
 *
 * No driver import: `pg` is owned by `src/platform/db/` (SDK boundary table).
 */

import type { DatabasePort } from "../../../platform/db/port";
import { PlatformError } from "../../../shared/errors";
import type { DispatchStatus, ModelCallOutcome } from "../domain/outcome";
import type {
  DispatchIntentInput,
  DispatchJournal,
  JournalAttempt,
} from "../ports/dispatch-journal";

interface AttemptRow {
  readonly id: string;
  readonly tenant_id: string;
  readonly application_id: string;
  readonly connection_id: string;
  readonly rail: string;
  readonly model: string;
  readonly request_hash: string;
  readonly admitted: boolean;
  readonly status: DispatchStatus;
  readonly outcome: unknown;
  readonly denial_reason: string | null;
  readonly created_at: Date | string;
  readonly resolved_at: Date | string | null;
}

function first<T>(rows: readonly T[]): T | undefined {
  return rows.length > 0 ? rows[0] : undefined;
}

function toAttempt(row: AttemptRow): JournalAttempt {
  return {
    id: row.id,
    tenantId: row.tenant_id,
    applicationId: row.application_id,
    connectionId: row.connection_id,
    rail: row.rail,
    model: row.model,
    requestHash: row.request_hash,
    admitted: row.admitted,
    status: row.status,
    outcome: row.outcome,
    createdAt:
      row.created_at instanceof Date ? row.created_at.toISOString() : String(row.created_at),
    resolvedAt:
      row.resolved_at === null
        ? null
        : row.resolved_at instanceof Date
          ? row.resolved_at.toISOString()
          : String(row.resolved_at),
  };
}

/**
 * The durable outcome payload: `outcomeClass` is constrained to the provider
 * axis by the journal CHECK constraint — `provider-success` or
 * `provider-failure`, never a quality/verification class (CON-005).
 */
function journalOutcomePayload(outcome: ModelCallOutcome): Record<string, unknown> {
  if (outcome.kind === "provider-success") {
    return {
      outcomeClass: "provider-success",
      stopReason: outcome.response.stopReason,
      usage: outcome.response.usage,
    };
  }
  return {
    outcomeClass: "provider-failure",
    category: outcome.failure.category,
    retryable: outcome.failure.retryable,
    providerCode: outcome.failure.providerCode,
    httpStatus: outcome.failure.httpStatus,
  };
}

export class SqlDispatchJournal implements DispatchJournal {
  constructor(private readonly db: DatabasePort) {}

  async recordIntent(input: DispatchIntentInput): Promise<void> {
    // Idempotent by attempt id (generated by the gateway per attempt).
    await this.db.execute({
      sql: `INSERT INTO models.dispatch_attempts
  (id, tenant_id, application_id, connection_id, rail, model, request_hash, admitted, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, TRUE, 'dispatching')
ON CONFLICT (id) DO NOTHING`,
      parameters: [
        input.id,
        input.tenantId,
        input.applicationId,
        input.connectionId,
        input.rail,
        input.model,
        input.requestHash,
      ],
    });
  }

  async recordDenial(input: DispatchIntentInput, reason: string): Promise<void> {
    await this.db.execute({
      sql: `INSERT INTO models.dispatch_attempts
  (id, tenant_id, application_id, connection_id, rail, model, request_hash, admitted, status, outcome, resolved_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, FALSE, 'denied', $8::jsonb, now())
ON CONFLICT (id) DO NOTHING`,
      parameters: [
        input.id,
        input.tenantId,
        input.applicationId,
        input.connectionId,
        input.rail,
        input.model,
        input.requestHash,
        JSON.stringify({ denied: true, reason }),
      ],
    });
  }

  async recordOutcome(
    attemptId: string,
    status: DispatchStatus,
    outcome: ModelCallOutcome,
  ): Promise<void> {
    const payload = JSON.stringify(journalOutcomePayload(outcome));
    const result = await this.db.execute({
      sql: `UPDATE models.dispatch_attempts
SET status = $2, outcome = $3::jsonb, resolved_at = now()
WHERE id = $1 AND status = 'dispatching'`,
      parameters: [attemptId, status, payload],
    });
    if (result.rowCount === 0) {
      throw new PlatformError({
        code: "PROVIDER_ERROR",
        message: "dispatch attempt row missing or already resolved",
        details: { attemptId },
      });
    }
  }

  async findAttempt(attemptId: string): Promise<JournalAttempt | null> {
    const result = await this.db.execute<AttemptRow>({
      sql: `SELECT id, tenant_id, application_id, connection_id, rail, model, request_hash,
admitted, status, outcome, denial_reason, created_at, resolved_at
FROM models.dispatch_attempts WHERE id = $1`,
      parameters: [attemptId],
    });
    const row = first(result.rows);
    return row === undefined ? null : toAttempt(row);
  }
}

/** Factory: composition roots and tests. */
export function createSqlDispatchJournal(db: DatabasePort): DispatchJournal {
  return new SqlDispatchJournal(db);
}
