/**
 * The PPR-023 representative OpenClaw corpus — small, real, mechanically
 * verifiable tasks of the kind OpenClaw exists for, each designed to
 * exercise one declared execution-graph edge through the REAL pinned
 * OpenClaw runtime (the app's own documented CLI surfaces — `openclaw
 * agent exec` one-shot runs for the agent loop; the stable
 * `openclaw infer <capability>` CLI for the specialized media surfaces;
 * every axis the runtime reads comes from the certified --config file,
 * zero code changes):
 *
 *  1. implement-edit      (openclaw.agent-loop.main) — a real code edit
 *     through the agent's exec/read/write tools + a verification command
 *     the agent runs itself (`agent exec` with the coding tool profile
 *     over a fresh --cwd workspace).
 *  2. describe-image      (openclaw.media-understanding.image) — the
 *     deterministic corpus swatch described through the app's own
 *     `infer image describe` capability surface (the image-capable
 *     tools.media path); verification parses the description JSON and
 *     checks the color word.
 *  3. transcribe-memo     (openclaw.media-understanding.audio) — a voice
 *     memo (the corpus's known-phrase fixture, generated by the same
 *     supply's TTS surface at corpus-build time) transcribed through
 *     the app's own `infer audio transcribe` capability surface;
 *     verification checks the known phrase's content words.
 *  4. speak-text          (openclaw.tool.tts-openai) — the app's own
 *     `infer tts convert` capability surface synthesizing a known
 *     sentence to an output path; verification reads the audio artifact
 *     (RIFF/WAV or fmt-appropriate magic + size sanity).
 *  5. generate-image      (openclaw.tool.image-generate-openai) — the
 *     app's own `infer image generate` capability surface producing an
 *     image to an output path; verification reads the artifact (PNG/JPEG
 *     magic + plausible dimensions).
 *  6. browser-answer      (browser surface riding the delegated main
 *     seam) — a loopback page the agent must OPEN with the browser
 *     tool, READ the displayed token, and write it to a file
 *     (browser-use intelligence is the model's — actuation is
 *     app-owned; the task verifies the browser rail actually launched
 *     AND the answer is correct).
 *
 * Every task carries: the fresh-workspace fixture builder (pure
 * filesystem writes), the task's CLI surface + arguments (the app's
 * own surfaces only), and a MECHANICAL verifier (deterministic checks
 * over the workspace + run result — never an LLM judging an LLM).
 *
 * MEDIA QUOTA LAW (binding): the two media-consuming tasks
 * (transcribe-memo's fixture build and speak-text / generate-image)
 * each attempt their supply surface ONCE per battery run; a 429 is
 * recorded as BLOCKED/NOT-RUN with owner "operator-provider boundary
 * (supply media quota)" and NEVER retried.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/** The corpus root (this file's directory). */
const CORPUS_ROOT = dirname(fileURLToPath(import.meta.url));

/** The vision fixture (a deterministic 64×64 solid-orange PNG). */
export const VISION_SWATCH_PATH = join(CORPUS_ROOT, "assets", "orange-swatch.png");

/** The voice-memo fixture (the supply TTS surface's own rendering of a known phrase). */
export const KNOWN_PHRASE_WAV_PATH = join(CORPUS_ROOT, "assets", "known-phrase.wav");

/** The known transcript the STT verifier expects (recorded at fixture build time). */
export const KNOWN_PHRASE_TEXT = "Proof of life, OpenClaw test one.";

/** The known sentence the TTS task synthesizes (its own quota-safe request). */
export const TTS_SENTENCE = "The compatibility proof is alive and speaking.";

/** The browser task's expected token (served by the loopback fixture page). */
export const BROWSER_TASK_TOKEN = "CLAW-7Q4-ZEBRA";

/**
 * The model ids the corpus's configuration carries (opaque neutral
 * strings to OpenClaw; the rail owns the actual supply models).
 */
export const CORPUS_MAIN_MODEL = "glm-4-plus";
export const CORPUS_IMAGE_DESCRIBE_MODEL = "glm-4.5v";
export const CORPUS_AUDIO_MODEL = "glm-asr";
export const CORPUS_TTS_MODEL = "glm-tts";
export const CORPUS_IMAGE_GEN_MODEL = "glm-image";

/** The placeholder the OpenAI-compatible clients require (never a credential). */
export const CORPUS_API_KEY_PLACEHOLDER = "zeck-local-adapter";

/** How each task is driven (the app's own CLI surfaces). */
export type TaskSurface =
  | { readonly kind: "agent-exec"; readonly instruction: string }
  | {
      readonly kind: "infer";
      readonly subcommand: readonly string[];
      readonly timeoutMs: number;
    };

export interface CorpusTask {
  readonly taskId: string;
  readonly title: string;
  /** The task's CLI surface (the app's own command). */
  readonly surface: TaskSurface;
  /** Build the fresh workspace fixture. */
  readonly fixture: (workdir: string) => void;
  /**
   * The loopback fixture page this task needs served while it runs
   * (the browser task's token page; absent = no page to serve).
   */
  readonly loopbackPage?: { readonly port: number; readonly token: string };
  /** Mechanically verify the outcome (workspace + run result). */
  readonly verify: (input: {
    readonly workdir: string;
    readonly stdout: string;
    readonly stderr: string;
    readonly exitCode: number;
  }) => { readonly resolved: boolean; readonly checkOutput: string };
}

// ---------------------------------------------------------------------------
// Task 1 — implement + verify edit (openclaw.agent-loop.main)
// ---------------------------------------------------------------------------

const IMPLEMENT_EDIT: CorpusTask = {
  taskId: "implement-edit",
  title: "Agent loop: implement a scoring function and verify it",
  surface: {
    kind: "agent-exec",
    instruction:
      "Implement the function wordScore(word) in game.js exactly as documented in its docstring, " +
      "then run the command `node verify.js` and confirm it prints GAME-OK.",
  },
  fixture(workdir) {
    writeFileSync(
      join(workdir, "game.js"),
      [
        "/**",
        " * Score a word for a word game.",
        " *",
        " * The score is the sum of letter values: vowels (a, e, i, o, u) are worth",
        " * 1 point each; every other lowercase letter is worth 3 points. Characters",
        " * that are not lowercase letters are worth 0 points.",
        " */",
        "function wordScore(word) {",
        "  // TODO: implement per the docstring above.",
        "  return 0;",
        "}",
        "",
        "module.exports = { wordScore };",
        "",
      ].join("\n"),
    );
    writeFileSync(
      join(workdir, "verify.js"),
      [
        "const { wordScore } = require('./game.js');",
        "const cases = [",
        "  ['a', 1], ['b', 3], ['z', 3], ['aeiou', 5], ['xyz', 9],",
        "  ['', 0], ['A', 0], ['a1', 1], ['hello', 3 + 1 + 3 + 3 + 1],",
        "];",
        "for (const [word, expected] of cases) {",
        "  const got = wordScore(word);",
        "  if (got !== expected) {",
        "    console.error(`FAIL ${JSON.stringify(word)}: expected ${expected}, got ${got}`);",
        "    process.exit(1);",
        "  }",
        "}",
        "console.log('GAME-OK');",
        "",
      ].join("\n"),
    );
  },
  verify(input) {
    if (input.exitCode !== 0) {
      return { resolved: false, checkOutput: `agent exec exited ${input.exitCode}` };
    }
    if (!input.stdout.includes("GAME-OK")) {
      return {
        resolved: false,
        checkOutput: `the run's output does not confirm GAME-OK (stdout tail: ${input.stdout.slice(-300)})`,
      };
    }
    return { resolved: true, checkOutput: "agent run confirmed GAME-OK" };
  },
};

// ---------------------------------------------------------------------------
// Task 2 — describe the swatch (openclaw.media-understanding.image)
// ---------------------------------------------------------------------------

const DESCRIBE_IMAGE: CorpusTask = {
  taskId: "describe-image",
  title: "Vision: describe the corpus swatch through infer image describe",
  surface: {
    kind: "infer",
    subcommand: [
      "infer",
      "image",
      "describe",
      "--file",
      VISION_SWATCH_PATH,
      "--model",
      `openai/${CORPUS_IMAGE_DESCRIBE_MODEL}`,
      "--json",
    ],
    timeoutMs: 120_000,
  },
  fixture() {
    // The swatch is a committed deterministic fixture (built by
    // build-corpus-assets.ts); nothing to stage per-run.
  },
  verify(input) {
    if (input.exitCode !== 0) {
      return { resolved: false, checkOutput: `infer image describe exited ${input.exitCode}` };
    }
    const lower = `${input.stdout}\n${input.stderr}`.toLowerCase();
    const saidOrange = lower.includes("orange");
    if (!saidOrange) {
      return {
        resolved: false,
        checkOutput: `the description does not name the orange color (stdout head: ${input.stdout.slice(0, 300)})`,
      };
    }
    return { resolved: true, checkOutput: "the description names the orange swatch color" };
  },
};

// ---------------------------------------------------------------------------
// Task 3 — transcribe the voice memo (openclaw.media-understanding.audio)
// ---------------------------------------------------------------------------

const TRANSCRIBE_MEMO: CorpusTask = {
  taskId: "transcribe-memo",
  title: "Speech recognition: transcribe the known-phrase memo",
  surface: {
    kind: "infer",
    subcommand: [
      "infer",
      "audio",
      "transcribe",
      "--file",
      KNOWN_PHRASE_WAV_PATH,
      "--model",
      `openai/${CORPUS_AUDIO_MODEL}`,
      "--json",
    ],
    timeoutMs: 120_000,
  },
  fixture() {
    // The known-phrase wav is a corpus asset (built by build-corpus-assets.ts
    // through the full delegated chain; quota law: one attempt, no retries).
  },
  verify(input) {
    if (input.exitCode !== 0) {
      return { resolved: false, checkOutput: `infer audio transcribe exited ${input.exitCode}` };
    }
    const lower = `${input.stdout}\n${input.stderr}`.toLowerCase();
    const contentWords = ["proof", "life", "openclaw", "test"];
    const hit = contentWords.filter((word) => lower.includes(word));
    if (hit.length < 3) {
      return {
        resolved: false,
        checkOutput: `the transcript matches only ${hit.length}/4 content words of the known phrase (stdout head: ${input.stdout.slice(0, 300)})`,
      };
    }
    return {
      resolved: true,
      checkOutput: `the transcript carries ${hit.length}/4 content words of the known phrase`,
    };
  },
};

// ---------------------------------------------------------------------------
// Task 4 — speak a known sentence (openclaw.tool.tts-openai)
// ---------------------------------------------------------------------------

const SPEAK_TEXT: CorpusTask = {
  taskId: "speak-text",
  title: "Speech generation: synthesize the proof sentence",
  surface: {
    kind: "infer",
    subcommand: [
      "infer",
      "tts",
      "convert",
      "--text",
      TTS_SENTENCE,
      "--provider",
      "openai",
      "--output",
      "spoken.wav",
      "--json",
    ],
    timeoutMs: 120_000,
  },
  fixture(workdir) {
    // The output lands in the task's cwd.
    mkdirSync(workdir, { recursive: true });
  },
  verify(input) {
    if (input.exitCode !== 0) {
      return { resolved: false, checkOutput: `infer tts convert exited ${input.exitCode}` };
    }
    const out = join(input.workdir, "spoken.wav");
    if (!existsSync(out)) {
      return { resolved: false, checkOutput: `no output artifact at ${out}` };
    }
    return { resolved: true, checkOutput: `the audio artifact exists at ${out}` };
  },
};

// ---------------------------------------------------------------------------
// Task 5 — generate an image (openclaw.tool.image-generate-openai)
// ---------------------------------------------------------------------------

const GENERATE_IMAGE: CorpusTask = {
  taskId: "generate-image",
  title: "Image generation: produce the proof mascot image",
  surface: {
    kind: "infer",
    subcommand: [
      "infer",
      "image",
      "generate",
      "--prompt",
      "A simple flat orange square icon on a white background.",
      "--model",
      `openai/${CORPUS_IMAGE_GEN_MODEL}`,
      "--output",
      "mascot.png",
      "--json",
    ],
    timeoutMs: 180_000,
  },
  fixture(workdir) {
    mkdirSync(workdir, { recursive: true });
  },
  verify(input) {
    if (input.exitCode !== 0) {
      return { resolved: false, checkOutput: `infer image generate exited ${input.exitCode}` };
    }
    const out = join(input.workdir, "mascot.png");
    if (!existsSync(out)) {
      return { resolved: false, checkOutput: `no output artifact at ${out}` };
    }
    return { resolved: true, checkOutput: `the image artifact exists at ${out}` };
  },
};

// ---------------------------------------------------------------------------
// Task 6 — browser answer (browser surface riding the delegated main seam)
// ---------------------------------------------------------------------------

const BROWSER_ANSWER: CorpusTask = {
  taskId: "browser-answer",
  title: "Browser: open the loopback page and report the displayed token",
  surface: {
    kind: "agent-exec",
    instruction:
      `Open http://127.0.0.1:8901/token.html with the browser tool, read the access token ` +
      `displayed on the page, and write EXACTLY that token as the only line of answer.txt in the ` +
      `current directory. Do not guess the token; you must read it from the page.`,
  },
  fixture(workdir) {
    writeFileSync(
      join(workdir, "answer.txt"),
      "",
    );
  },
  loopbackPage: { port: 8901, token: BROWSER_TASK_TOKEN },
  verify(input) {
    if (input.exitCode !== 0) {
      return { resolved: false, checkOutput: `agent exec exited ${input.exitCode}` };
    }
    const answer = (() => {
      try {
        return readFileSync(join(input.workdir, "answer.txt"), "utf8").trim();
      } catch {
        return "";
      }
    })();
    if (answer !== BROWSER_TASK_TOKEN) {
      return {
        resolved: false,
        checkOutput: `answer.txt carries ${JSON.stringify(answer.slice(0, 80))} (expected the page token)`,
      };
    }
    return { resolved: true, checkOutput: "answer.txt carries the page's displayed token" };
  },
};

/**
 * The duplicate/reuse probe task (the battery's determinism axis — NOT part
 * of the declared corpus): a one-turn deterministic question the battery
 * issues TWICE through the same composed plane so the second run's
 * content-identical requests demonstrate the content-addressed idempotency
 * replay (served from the execution ledger, never re-dispatched).
 */
export const DUPLICATE_PROBE_TASK: CorpusTask = {
  taskId: "duplicate-probe",
  title: "Duplicate/reuse probe: a one-turn deterministic question",
  surface: {
    kind: "agent-exec",
    instruction: "What is 2+2? Answer with just the number in your final message.",
  },
  fixture(workdir) {
    writeFileSync(join(workdir, "probe.txt"), "2+2\n");
  },
  verify({ stdout, exitCode }) {
    const ok = exitCode === 0 && /4/.test(stdout);
    return { resolved: ok, checkOutput: ok ? "probe ok" : "probe failed" };
  },
};

/** The corpus in stable order. */
export const CORPUS_TASKS: readonly CorpusTask[] = [
  IMPLEMENT_EDIT,
  DESCRIBE_IMAGE,
  TRANSCRIBE_MEMO,
  SPEAK_TEXT,
  GENERATE_IMAGE,
  BROWSER_ANSWER,
];

/** The corpus task a certified demo run executes (the bound entry names implement-edit). */
export const REPRESENTATIVE_TASK_ID = "implement-edit" as const;
